config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

   root 'welcome#index'

   resources :users
   resources :items do
     get :upvote, on: :member
   end
   get    'signup' => 'users#new', as: 'signup'
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :price, {numericality: {greater_than: 0, allow_nil: false} }
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def render_403
    render file: "public/403.html", status: 403
  end

  def render_404
    render file: "public/404.html", status: 404
  end

  def check_if_admin
    render_403 unless current_user
  end
end

app/controllers/auth_controller.rb
#fully custom version of auth
class AuthController < ApplicationController
  def reg
  end

  def do_reg
    @user = User.create(email:params[:email],name:params[:name],password: Digest::MD5.hexdigest(params[:password]))
    if @user.errors.empty?
      redirect_to root_path
    else
     flash[:status] = "Error here"
     redirect_to reg_path
    end
  end

  def login
  end

  def do_login
    @user = User.where('login = ?',params[:email])
    if @user.blank?
      redirect_to login_path
    else
      session[:user] = @user
      redirect_to root_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :check_if_admin, only: [:new,:show,:edit,:update]
  before_filter :find_item, only: [:show,:edit,:update,:destroy,:upvote]

  def index
    @items = Item.all
    @items = Item.paginate(:page => params[:page], :per_page => 2)
  end

  #/items/1 GET
  def show
    unless @item
      render text: "Page not found",status:404
    end
  end

  #/items/new GET
  def edit
  end

  #/items/1 PUT
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "edit"
    end
  end

  #/items/1/edit GET
  def new
    @item = Item.new
  end

  # /items POST
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "new"
    end
  end

  # /items/1 DELETE
  def destroy
    @item.destroy
    redirect_to action: :index
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  private
  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def item_params
    params.require(:item).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>
    <%= render 'shared/error_messages', :model => @item   %>
    <p><div>Цена: </div><%= f.text_field :price %></p>
    <p><div>Название: </div><%= f.text_field :name %></p>
    <p><div>Описание: </div><%= f.text_field :description %></p>
    <p><div>Вес: </div><%= f.text_field :weight %></p>
    <p>
      <%= f.submit "Обновить товар" %>
    </p>
<% end %>

app/views/items/index.html.erb
<h1>Items list</h1>
<% if @items.empty? %>
    <b>No items in store</b>
<% else %>
    <table class="table">
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @items.each do |i| %>
          <tr>
            <td><%= i.id %></td>
            <td><%= link_to i.name, item_path(i) %></td>

            <td><%= i.price %> руб.</td>
            <td><%= link_to 'Редактировать', edit_item_path(i) %></td>
            <td><%= link_to "Удалить", i, method: :delete,data: {confirm:"Вы дейвствительно хотите удалить товар?"} %></td>
            <td>Рейтинг: <%= i.votes_count %>,<%= link_to "+",upvote_item_path(i) %></td>
          </tr>
      <% end %>
    </table>
    <%= will_paginate @items %>

<% end %>

<p><%= link_to 'Добавить', new_item_path %></p>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>
    <%= render 'shared/error_messages', :model => @item %>
    <p><div>Цена: </div><%= f.text_field :price %></p>
    <p><div>Название: </div><%= f.text_field :name %></p>
    <p><div>Описание: </div><%= f.text_field :description %></p>
    <p><div>Вес: </div><%= f.text_field :weight %></p>
    <p>
      <%= f.submit "Создать товар" %>
    </p>
<% end %>

app/views/items/show.html.erb
<p>Сведения о товаре</p>
<h1><%=@item.name%></h1>

<ul>
  <li><%= @item.price %>руб.</li>
  <li><%= @item.description %></li>
  <li>Вес: <%= @item.weight %> кг.</li>
</ul>
<%= link_to 'Редактировать', edit_item_path(@item) %>
<a><%= link_to 'Назад', items_path %></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Items", items_path %></li>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(model.errors.count, "error") %>.
      </div>
      <ul>
        <% model.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="row">
        <h1>Sign up</h1>
    </div>
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', :model => @user  %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <%= gravatar_for @user %>
    <section class="user_info">
      <div>
        <label>Login: </label> <%= @user.name %>
      </div>
      <div>
        <label>Email: </label> <%= @user.email %>
      </div>
    </section>
  </aside>
</div>

app/views/welcome/index.html.erb
<h1>It's main page</h1>